-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Approved_Students"
(
    "Lecturer_ID" integer NOT NULL,
    "Student_ID" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Employer"
(
    "ID" integer NOT NULL,
    "Email" character varying COLLATE pg_catalog."default" NOT NULL,
    "Password" character varying COLLATE pg_catalog."default" NOT NULL,
    "Fullname" character varying COLLATE pg_catalog."default" NOT NULL,
    "Description" character varying COLLATE pg_catalog."default" NOT NULL,
    "Image" bytea,
    "Phone" character varying COLLATE pg_catalog."default",
    "Address" character varying COLLATE pg_catalog."default",
    "IsInternshipRemote" boolean NOT NULL,
    "IsWorkRemote" boolean NOT NULL,
    "City" character varying COLLATE pg_catalog."default" NOT NULL,
    "AccountType" integer DEFAULT 3,
    CONSTRAINT "Employer_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Employer_Languages"
(
    "Employer_ID" integer NOT NULL,
    "Languages_ID" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Employer_Technologies"
(
    "Employer_ID" integer NOT NULL,
    "Technologies_ID" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."JobPost"
(
    "ID" integer NOT NULL,
    "Title" character varying COLLATE pg_catalog."default" NOT NULL,
    "Description" character varying COLLATE pg_catalog."default" NOT NULL,
    "Role" character varying COLLATE pg_catalog."default" NOT NULL,
    "IsRemote" boolean NOT NULL,
    "Salary" integer NOT NULL,
    CONSTRAINT "JobPost_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Languages"
(
    "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "LangName" character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Languages_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Lecturer"
(
    "ID" integer NOT NULL,
    "Email" character varying COLLATE pg_catalog."default" NOT NULL,
    "Password" character varying COLLATE pg_catalog."default" NOT NULL,
    "Fullname" character varying COLLATE pg_catalog."default" NOT NULL,
    "Description" character varying COLLATE pg_catalog."default" NOT NULL,
    "Image" bytea,
    "Phone" character varying COLLATE pg_catalog."default",
    "Address" character varying COLLATE pg_catalog."default",
    "AccountType" integer DEFAULT 2,
    CONSTRAINT "Lecturer_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Post"
(
    "ID" integer NOT NULL,
    "Title" character varying COLLATE pg_catalog."default" NOT NULL,
    "Description" character varying COLLATE pg_catalog."default" NOT NULL,
    "Role" character varying COLLATE pg_catalog."default" NOT NULL,
    "Company" character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Post_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Post_Technologies"
(
    "Post_ID" integer NOT NULL,
    "Technologies_ID" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Student"
(
    "ID" integer NOT NULL,
    "Email" character varying COLLATE pg_catalog."default" NOT NULL,
    "Password" character varying COLLATE pg_catalog."default" NOT NULL,
    "Fullname" character varying COLLATE pg_catalog."default" NOT NULL,
    "Description" character varying COLLATE pg_catalog."default" NOT NULL,
    "Image" bytea,
    "Phone" character varying COLLATE pg_catalog."default",
    "Address" character varying COLLATE pg_catalog."default",
    "School" character varying COLLATE pg_catalog."default" NOT NULL,
    "City" character varying COLLATE pg_catalog."default" NOT NULL,
    "AccountType" integer DEFAULT 1,
    CONSTRAINT "Student_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Student_Applies_Job"
(
    "Student_ID" integer NOT NULL,
    "JobPost_ID" integer NOT NULL,
    "isAccepted" boolean
);

CREATE TABLE IF NOT EXISTS public."Student_Languages"
(
    "Student_ID" integer NOT NULL,
    "Languages_ID" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Student_Technologies"
(
    "Student_ID" integer NOT NULL,
    "Technologies_ID" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Technologies"
(
    "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TechName" character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Technologies_pkey" PRIMARY KEY ("ID")
);

ALTER TABLE IF EXISTS public."Approved_Students"
    ADD CONSTRAINT "Approved_Students_Lecturer_ID_fkey" FOREIGN KEY ("Lecturer_ID")
    REFERENCES public."Lecturer" ("ID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Approved_Students"
    ADD CONSTRAINT "Approved_Students_Student_ID_fkey" FOREIGN KEY ("Student_ID")
    REFERENCES public."Student" ("ID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Employer_Languages"
    ADD CONSTRAINT "Employer_Languages_Employer_ID_fkey" FOREIGN KEY ("Employer_ID")
    REFERENCES public."Employer" ("ID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Employer_Languages"
    ADD CONSTRAINT "Employer_Languages_Languages_ID_fkey" FOREIGN KEY ("Languages_ID")
    REFERENCES public."Languages" ("ID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Employer_Technologies"
    ADD CONSTRAINT "Employer_Technologies_Employer_ID_fkey" FOREIGN KEY ("Employer_ID")
    REFERENCES public."Employer" ("ID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Employer_Technologies"
    ADD CONSTRAINT "Employer_Technologies_Technologies_ID_fkey" FOREIGN KEY ("Technologies_ID")
    REFERENCES public."Technologies" ("ID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."JobPost"
    ADD CONSTRAINT "JobPost_ID_fkey" FOREIGN KEY ("ID")
    REFERENCES public."Employer" ("ID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;
CREATE INDEX IF NOT EXISTS "JobPost_pkey"
    ON public."JobPost"("ID");


ALTER TABLE IF EXISTS public."Post"
    ADD CONSTRAINT "Post_ID_fkey" FOREIGN KEY ("ID")
    REFERENCES public."Student" ("ID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "Post_pkey"
    ON public."Post"("ID");


ALTER TABLE IF EXISTS public."Post_Technologies"
    ADD CONSTRAINT "Post_Technologies_Post_ID_fkey" FOREIGN KEY ("Post_ID")
    REFERENCES public."Post" ("ID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Post_Technologies"
    ADD CONSTRAINT "Post_Technologies_Technologies_ID_fkey" FOREIGN KEY ("Technologies_ID")
    REFERENCES public."Technologies" ("ID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Student_Applies_Job"
    ADD CONSTRAINT "Student_Applies_Job_JobPost_ID_fkey" FOREIGN KEY ("JobPost_ID")
    REFERENCES public."JobPost" ("ID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Student_Applies_Job"
    ADD CONSTRAINT "Student_Applies_Job_Student_ID_fkey" FOREIGN KEY ("Student_ID")
    REFERENCES public."Student" ("ID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Student_Languages"
    ADD CONSTRAINT "Student_Languages_Languages_ID_fkey" FOREIGN KEY ("Languages_ID")
    REFERENCES public."Languages" ("ID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Student_Languages"
    ADD CONSTRAINT "Student_Languages_Student_ID_fkey" FOREIGN KEY ("Student_ID")
    REFERENCES public."Student" ("ID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Student_Technologies"
    ADD CONSTRAINT "Student_Technologies_Student_ID_fkey" FOREIGN KEY ("Student_ID")
    REFERENCES public."Student" ("ID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Student_Technologies"
    ADD CONSTRAINT "Student_Technologies_Technologies_ID_fkey" FOREIGN KEY ("Technologies_ID")
    REFERENCES public."Technologies" ("ID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;