-- MySQL Script generated by MySQL Workbench
-- Tue Dec  6 22:02:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LinkedKTU
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LinkedKTU
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LinkedKTU` DEFAULT CHARACTER SET utf8 ;
USE `LinkedKTU` ;

-- -----------------------------------------------------
-- Table `LinkedKTU`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LinkedKTU`.`Student` (
  `ID` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Fullname` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(100) NULL,
  `Image` BLOB NULL,
  `Phone` VARCHAR(10) NULL,
  `Address` VARCHAR(100) NULL,
  `School` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LinkedKTU`.`Lecturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LinkedKTU`.`Lecturer` (
  `ID` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Fullname` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(100) NULL,
  `Image` BLOB NULL,
  `Phone` VARCHAR(10) NULL,
  `Address` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LinkedKTU`.`Employer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LinkedKTU`.`Employer` (
  `ID` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Fullname` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(100) NULL,
  `Image` BLOB NULL,
  `Phone` VARCHAR(10) NULL,
  `Address` VARCHAR(100) NULL,
  `IsInternshipRemote` TINYINT NOT NULL,
  `IsWorkRemote` TINYINT NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LinkedKTU`.`Approved_Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LinkedKTU`.`Approved_Students` (
  `Student_ID` INT NOT NULL,
  `Lecturer_ID` INT NOT NULL,
  PRIMARY KEY (`Student_ID`, `Lecturer_ID`),
  INDEX `fk_Student_has_Lecturer_Lecturer1_idx` (`Lecturer_ID` ASC) VISIBLE,
  INDEX `fk_Student_has_Lecturer_Student_idx` (`Student_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Student_has_Lecturer_Student`
    FOREIGN KEY (`Student_ID`)
    REFERENCES `LinkedKTU`.`Student` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Lecturer_Lecturer1`
    FOREIGN KEY (`Lecturer_ID`)
    REFERENCES `LinkedKTU`.`Lecturer` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LinkedKTU`.`Languages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LinkedKTU`.`Languages` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Lang_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LinkedKTU`.`Technologies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LinkedKTU`.`Technologies` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Tech_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
